### ISSUE TITLE
How to find the camera URL

### ISSUE THREAD

**Issue by nbibin001** [grubernaut/camera-widget#5]
I have an IP camera and was trying to interface it with the dashing dashboard. I have its IP address, connection username and password, but not sure what to give for the camera1URL in the cameras.erb file under the jobs folder. The example shows @camera1URL = "/mobile/channel01.jpg". How do we know this path ? Appreciate your help.

**Comment by grubernaut** [comment]
Hey @nbibin001, thanks for the issue! 
It's been a long while since I used this, or worked on it. It looks like `camera1URL` should probably be named `path` or something similar. 
ie: 
```
<cameraIP>:<cameraPort>/<cameraURL>
```

Hope this helps, thanks!
